name: Make PDF
on: [push]
jobs:
  Make-PDF:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install needed packages using APT
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-reccomended cmake

      - name: Make PDF
        run: |
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: GDD
          path: main.pdf