name: Make PDF
on: [push]
jobs:
  Make-PDF:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages using APT
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full cmake
      - name: List files in the repository
        run: |
          cd ${{ github.workspace }} && make
