name: Make PDF
on: [push]
jobs:
  Make-PDF:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: '.'

      - name: Install needed packages using APT & TLMGR
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-recommended cmake
          sudo tlmgr init-usertree
          sudo tlmgr install enumitem

      - name: Make PDF
        run: |
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GDD
          path: main.pdf
