name: Make PDF
on: [push]
jobs:
  Make-PDF:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: '.'
      
      - uses: wtfjoke/setup-tectonic@v3

      - name: Make PDF
        run: |
          tectonic main.tex
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GDD.pdf
          path: main.pdf